language: en

pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
- name: EntitySynonymMapper
- name: ResponseSelector

policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: TEDPolicy
assistant_id: 20250319-033213-mint-balance
